### ISSUE TITLE
Other issues

### ISSUE THREAD

**Issue by SighDuck265** [mcfullard/ttd-release#2]
The score does not reset correctly when playing a new game.
The score did not register on level 1 of my first try, it only started registering after I hit level 2.

**Comment by mcfullard** [comment]
@SighDuck265 thanks for this issue. Could you perhaps include a screenshot? @Bas24live will you please take care of this? It seems like it could be in your department

**Comment by Bas24live** [comment]
I have seen this bug and will fix it as soon as possible, thanx.

**Comment by RhysBotes** [comment]
@Bas24live 
![ttd issue](https://cloud.githubusercontent.com/assets/15180874/10564303/de5b8404-75ae-11e5-9d92-4ef2fdbc9459.PNG)

**Comment by mcfullard** [comment]
Bas fixed.
